#!/usr/bin/env ruby
# Docker Event Listener / DDNS
# Original author: Kelly Becker <kbecker@kellybecker.me>
#         Website: http://kellybecker.me
# Original Code: https://gist.github.com/KellyLSB/4315a0323ed0fe1d79b6
# Changes by: Esa Varemo <esa@kuivanto.fi>
# License: MIT

# Set up a proper logger
require 'logger'
log_file = ARGV.first || '-'
log = Logger.new(log_file == '-' ? $stdout : log_file)

# Create a PID file for this service
File.open('/var/run/docker_ddns.pid', 'w+') { |f| f.write($$) }

# Capture the terminate signal
trap("INT") do
#  log.info "Caught INT Signal... Exiting."
  File.unlink('/var/run/docker_ddns.pid')
  puts "Stopped"
  exit
end

# Welcome message
log.info "Starting Docker Dynamic DNS - Event Handler"
log.info "Original author: Kelly Becker <kbecker@kellybeckr.me>"
log.info "        Website: http://kellybecker.me"
log.info "Modified by: Esa Varemo <esa@kuivanto.fi>"


# Listen To Docker.io Events
events = IO.popen('docker events')

# Keep Listening for incoming data
while line = events.gets

  # Container Configuration
  ENV['CONTAINER_EVENT']    = line.split.last
  ENV['CONTAINER_CID_LONG'] = line.gsub(/^.*([0-9a-f]{64}).*$/i, '\1')
  ENV['CONTAINER_CID']      = ENV['CONTAINER_CID_LONG'][0...12]

  # Event Fired info
  log.info "Event Fired (#{ENV['CONTAINER_CID']}): #{ENV['CONTAINER_EVENT']}."

  case ENV['CONTAINER_EVENT']
    when 'start'

      # Get Container Details for DNS
      ENV['CONTAINER_IP_ADDR']  = %x{docker inspect --format='{{.NetworkSettings.IPAddress}}' $CONTAINER_CID_LONG }.strip
      ENV['CONTAINER_HOSTNAME'] = %x{docker inspect --format='{{.Config.Hostname}}' $CONTAINER_CID_LONG}.strip
      ENV['CONTAINER_NAME'] =     %x{docker inspect --format='{{.Name}}' $CONTAINER_CID_LONG}.strip.gsub('/', '')

      system("cli53 rrcreate #{ENV['DOMAIN']} \"#{ENV['CONTAINER_CID']} 60 A #{ENV['CONTAINER_IP_ADDR']}\"")
      if $?.success?
        log.info "Updated Docker DNS (#{ENV['CONTAINER_CID']}): #{ENV['CONTAINER_HOSTNAME']}.#{ENV['NET_DOMAIN']} 60 A #{ENV['CONTAINER_IP_ADDR']}."
      else
        log.error "We could not update the A record for #{ENV['CONTAINER_CID']}. Please check your nsupdate keys."
      end

      system("cli53 rrcreate #{ENV['DOMAIN']} \"#{ENV['CONTAINER_NAME']} 60 CNAME #{ENV['CONTAINER_CID']}\"")
      if $?.success?
        log.info "Added alias (#{ENV['CONTAINER_CID']}): #{ENV['CONTAINER_NAME']} 60 CNAME #{ENV['CONTAINER_HOSTNAME']}"
      else
        log.error "We could not update the CNAME record for #{ENV['CONTAINER_CID']}. Please check your nsupdate keys."
      end
    when 'die'
      # Get Container Details for DNS
      ENV['CONTAINER_IP_ADDR']  = %x{docker inspect $CONTAINER_CID_LONG | grep '"IPAddress"'}.strip.gsub(/[^0-9\.]/i, '')
      ENV['CONTAINER_HOSTNAME'] = %x{docker inspect $CONTAINER_CID_LONG| grep '"Hostname"' | awk '{print $NF}'}.strip.gsub(/^"(.*)",/i, '\1')
      ENV['CONTAINER_NAME'] =     %x{docker inspect --format='{{.Name}}' $CONTAINER_CID_LONG}.strip.gsub('/', '')

      system("cli53 rrdelete #{ENV['DOMAIN']} #{ENV['CONTAINER_HOSTNAME']} A")
      if $?.success?
        log.info "Deleted A record (#{ENV['CONTAINER_CID']}): #{ENV['CONTAINER_HOSTNAME']}.#{ENV['NET_DOMAIN']}."
      else
        log.error "We could not update the Docker DNS records for #{ENV['CONTAINER_CID']}. Please check your nsupdate keys."
      end

      system("cli53 rrdelete #{ENV['DOMAIN']} #{ENV['CONTAINER_NAME']} CNAME")
      if $?.success?
        log.info "Deleted CNAME record (#{ENV['CONTAINER_CID']}): #{ENV['CONTAINER_NAME']}.#{ENV['NET_DOMAIN']}."
      else
        log.error "We could not update the Docker DNS records for #{ENV['CONTAINER_CID']}. Please check your nsupdate keys."
      end
  end
end

exit